name: "Cypress e2e test advanced API"
on: workflow_call
jobs:
  cypress-run:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the App 1
        run: cd advanced-api/automatic-vendor-sharing/app1; yarn install; yarn start

      - name: Build the App 2
        run: cd advanced-api/automatic-vendor-sharing/app2; yarn install; yarn start

      - name: Cypress tests
        uses: cypress-io/github-action@v5
        with:
          wait-on: 'http://localhost:3001, http://localhost:3002'
          browser: chrome
          config-file: ./cypress/config/cypress.config.ts
          spec: ./advanced-api/automatic-vendor-sharing/e2e/*.cy.ts