name: "Cypress e2e test"
on: 
  push:
      branches:
      - 'setup-ci'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        list-files: json
        filters: |
          added:
            - added: "**"
          deleted:
            - deleted: "**"
          modified:
            - modified: "**"
          any:
            - added|deleted|modified: "*"

    - name: Print 'added_files'
      run: echo ${{steps.filter.outputs.added_files}}
    - name: Print 'modified_files'
      run: echo ${{steps.filter.outputs.modified_files}}
    - name: Print 'deleted_files'
      run: echo ${{steps.filter.outputs.deleted_files}}
    - name: Print 'any'
      run: echo ${{steps.filter.outputs.any_files}}

#   advancedApiTests-automaticVendorSharing:
#         uses: ./.github/workflows/advanced-api-automatic-vendor-sharing-cypress-tests.yml

#   advancedApiTests-dynamicReports:
#         uses: ./.github/workflows/advanced-api-dynamic-remotes-cypress-tests.yml